### PR TITLE
Use None instead of string 'None'

### PR DESCRIPTION
**Pull request by sergio-costas**
Two command line options use the string 'None' instead of the native type None as the default value.

This PR changes this.

### CODE REVIEW

**Comment by rudra-iitm** [comment]
I think there is an issue when using None instead of 'None', as action.yml sends 'None' when an argument is not passed. We can't pass None as the default value in action.yml because it breaks.

**Comment by sergio-costas** [comment]
I updated the action.yml file. Now it should manage that case without problem.

**Comment by sergio-costas** [comment]
Hi @rudra-iitm . Could you review this patch, please? I want to be sure that it doesn't break anything.

**Comment by rudra-iitm** [comment]
@sergio-costas , this looks good to me.

**Pull request merged**
