### PR TITLE
support tracks for automation tools + added gaming-graphics

### PR DESCRIPTION
**Pull request by jssotomdz**
1. Adding gaming-graphics-core22 to the test suite
2. Adding an extra column in snaps.py for track
3. Had to change the snapchanges API call since /details doesn't find a snap if that snap doesn't have something posted to latest/stable

Planning on doing some refactoring afterwards

### CODE REVIEW

**Comment by kenvandine** [comment]
@seb128 can you please take a look at this?  Note this should be useful for firefox's esr track as well.

**Comment by seb128** [comment]
Thanks for the work there and sorry for the delay reviewing. I've some notes and questions

Could you split the changes in different commits (one for handling the different tracks, one changing the store api for the query, one to add the gaming snaps)

I've been uncertain about the definition table format for a while and I wonder if it makes sense to add one more items to the lines definition. If having another track is a special case should we maybe have another dictionary listing snaps that use a non standard tracks instead? What do you think?

**Comment by jssotomdz** [comment]
> Thanks for the work there and sorry for the delay reviewing. I've some notes and questions
> 
> Could you split the changes in different commits (one for handling the different tracks, one changing the store api for the query, one to add the gaming snaps)
> 
> I've been uncertain about the definition table format for a while and I wonder if it makes sense to add one more items to the lines definition. If having another track is a special case should we maybe have another dictionary listing snaps that use a non standard tracks instead? What do you think?

Separated the changes in three commits as suggested. Regarding the dictionary for channels, I was talking with Ken about that. Right now it is only a matter of adding the channel in the extra column. The other way I see this could work would be to add an extra dictionary with the tracked tracks. If the snap isn't in this new dict, only check latest. Otherwise check the channels contained in the dict object (key: name of the snap, value: list of tracks?). But this will of course require code changes to parse both the original table and now the new dict. And of course logic to execute "n" times one for each channel. Is the extra code complexity worth it?

Let me know what you think and if the decision is to add the dictionary I'll work on the changes

**Review by seb128 — APPROVED** [review]
Thanks for splitting the commits. And you convinced me, let's add one more parameter to the table!

**Pull request merged**
