### PR TITLE
Create style check shell script

### PR DESCRIPTION
**Pull request by sergio-costas**
This PR moves all the style checks into scripts. This allows to run them locally before doing a push. It also will allow to easily add extra style checks, like flake8.

Also, it renames the unitary test scripts to *unittests.py* in all cases, adding a CONTRIBUTING.md file too.

### CODE REVIEW

**Comment by hellsworth** [comment]
seems good. thanks!

**Comment by hellsworth** [comment]
Ah, a rebase is needed.

**Comment by sergio-costas** [comment]
Rebase done.

**Comment by sergio-costas** [comment]
I merged it since you approved it :-)

**Comment by hellsworth** [comment]
Thanks!!

**Pull request merged**
